version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: frauddb
      POSTGRES_USER: fraud
      POSTGRES_PASSWORD: fraud123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fraud -d frauddb"]
      interval: 5s
      timeout: 5s
      retries: 5

  ml-service:
    build: ./ml-service
    container_name: ml-service
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/docs')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
      ml-service:
        condition: service_started
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/frauddb
      - DB_USER=fraud
      - DB_PASSWORD=fraud123
      - JWT_SECRET=mySuperSecretJwtTokenWithAtLeast256BitsForHmacSha256SignatureAlgorithm
      - ML_SERVICE_URL=http://ml-service:8000

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
